version: '3.8'

services:
  aviator_bot:
    build: .
    env_file:
      - archivo.env
    restart: always

environment:
  - SOCKS_PROXY=socks5://192.252.216.81:4145
  - API_KEY=8003841250:AAHhSeVuAvuPYpOzucRZMgu8xoAz9x-TadM
  - WS_URL=wss://cf.1win.direct/v4/socket.io/?Language=es&xorigin=1win.com&EIO=4&transport=websocket
  - TELEGRAM_TOKEN=8003841250:AAHhSeVuAvuPYpOzucRZMgu8xoAz9x-TadM
  - CHAT_ID=1985047351
  - PREDICTION_THRESHOLD=2.0